language: node_js
node_js:
  - "7"
cache:
  directories:
    - node_modules
    - build

install:
  - npm install

addons:
  sonarcloud:
    organization: "nesqwik-github" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN # encrypted value of your token
    branches:
      - master
      - develop
      - feature/[a-zA-Z0-9]*

script:
  - npm test -- --coverage --runInBand
  - sonar-scanner
  - npm run build
