language: node_js
node_js:
  - "7"
cache:
  directories:
    - node_modules
    - build

install:
  - npm install

addons:
  sonarcloud:
    organization: "nesqwik-github" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN # encrypted value of your token

script:
  - npm test -- --coverage
  - sonar-scanner
  - npm run build
  - mkdir -p to_deploy/prod
  - cp build/* to_deploy/prod/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: to_deploy
  on:
    branch: master
